### PR TITLE
Using library with Python3 gives TypeError: a bytes-like object is required, not 'str'

### PR DESCRIPTION
**Pull request by sergeymazin**
This minor change makes python-bareos compatible with Python 3.5.

Please review and let me know if there is anything else I need to do to get it merged.

@joergsteffens

### CODE REVIEW

**Comment by joergsteffens** [comment]
Thank you for your patch. However, I'd need more explanation, as some of your changes contradict the changes I've done to enable Python3 support: 3c3b7a5da5c3f370b5a75bf5a0295ebe4c660acb
I switched to ByteArrays to get a compatible way for Python2 and Python3.

I normally use Python2, so maybe you approach is better, but I'd like some explanation, so that I understand what is going on.

What error did occur in your environment without this patch and how can I reproduce it?

regards,
Jörg

**Comment by sergeymazin** [comment]
Thanks for you comments, Jörg.

What I do is I build this package with Python3.5 and try to connect to Director service, but get error back. This minor change fixes it and does not break it for Python2.7.

It builds OK:
```
python3.5 setup.py build
sudo python3.5 setup.py install
```

But later I get:
```
>>> import bareos.bsock
>>> password=bareos.bsock.Password(pwd)
>>> directorconsole=bareos.bsock.DirectorConsoleJson(address=host, port=9101, password=password)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sergey/PycharmProjects/python-bareos-source/bareos/bsock/directorconsolejson.py", line 15, in __init__
    super(DirectorConsoleJson, self).__init__(*args, **kwargs)
  File "/Users/sergey/PycharmProjects/python-bareos-source/bareos/bsock/directorconsole.py", line 19, in __init__
    self.auth(name=name, password=password, auth_success_regex=b'^1000 OK.*$')
  File "/Users/sergey/PycharmProjects/python-bareos-source/bareos/bsock/lowlevel.py", line 77, in auth
    return self.__auth()
  File "/Users/sergey/PycharmProjects/python-bareos-source/bareos/bsock/lowlevel.py", line 90, in __auth
    self.recv_msg(self.auth_success_regex)
  File "/Users/sergey/PycharmProjects/python-bareos-source/bareos/bsock/lowlevel.py", line 202, in recv_msg
    lastlineindex = self.receive_buffer.rfind('\n') + 1
TypeError: a bytes-like object is required, not 'str'
```

**Comment by sergeymazin** [comment]
Actually,
I updated PR and it should look better now @joergsteffens

**Comment by joergsteffens** [comment]
So, do I only need to integrate your last commit 39b4ffa2a4d639e8120247fa0b87808e987ce491 ? Very well possible, as I added the rfind('\ņ') function after I tested with python 3.

If I only need to include the last commit, you should overwrite your pull request with only the single commit, otherwise I can not merge them easily.

**Comment by sergeymazin** [comment]
I am not github guru so I just recreated PR with only last change in it

**Pull request closed without merging**
